name: Add important packages for compile packages
on:
  workflow_dispatch:
jobs:
  update_db:
    runs-on: ubuntu-latest
    steps: 
      - uses: antman666/update-db-for-repo@single
        with: 
          tag: x86_64
      - uses: ncipollo/release-action@v1.10.0
        with:
          allowUpdates: True
          tag: "x86_64"
          artifacts: "./action-repo.*"
          token: ${{ secrets.GITHUB_TOKEN }}
